# Generated by Django 4.2.1 on 2023-07-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='productos')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipo', models.CharField(max_length=100)),
                ('metodo_pago', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='apellido',
            new_name='nombrecompleto',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='nombre',
        ),
    ]
