# Generated by Django 4.2.1 on 2023-07-10 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0004_formulario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
    ]
