# Generated by Django 4.2.1 on 2023-07-11 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0005_remove_producto_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tipo',
        ),
    ]
