# Generated by Django 4.2.1 on 2023-07-11 00:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0006_remove_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categorias',
            field=models.CharField(default='Sin categoría', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='diagnostico',
            field=models.CharField(default='Sin categoría', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='producto',
            name='mecanico',
            field=models.CharField(default='Sin categoría', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='repuestos',
            field=models.CharField(default='Sin categoría', max_length=100),
        ),
    ]
